// ★ v0.37.0 — Mobile Shop Floor 회귀 (SPEC v0.1 §5 · GPT 5조건 · 실기기 검증은 별도 수동)
const fs = require('fs'), path = require('path');
const { JSDOM, VirtualConsole } = require(path.join(__dirname, 'node_modules/jsdom'));
const html = fs.readFileSync(path.join(__dirname, 'vela-mes-prototype.html'), 'utf8');
const stripped = html.replace(/<script\s+src=[^>]*><\/script>/g, '').replace(/<link\s+rel="manifest"[^>]*>/g, '');
const scripts = [...stripped.matchAll(/<script\b(?![^>]*\bsrc=)[^>]*>([\s\S]*?)<\/script>/g)].map(m => m[1]);
function boot(opts){
  const dom = new JSDOM(stripped, { runScripts:'outside-only', pretendToBeVisual:true, virtualConsole:new VirtualConsole(), url:'http://localhost/' });
  const win = dom.window; win.VELA_BACKEND = 'local';
  win.XLSX = { utils:{book_new:()=>({}),json_to_sheet:()=>({}),book_append_sheet:()=>{}}, writeFile:()=>{} };
  win.Html5Qrcode = function(){}; win.qrcode = function(){ return { addData(){}, make(){}, createSvgTag(){return ''}, createDataURL(){return ''} }; };
  win.prompt = () => '검증 사유';
  win.__osDark = !!(opts && opts.osDark);
  win.matchMedia = q => ({ get matches(){ return (/pointer:\s*coarse/.test(q) && !!(opts && opts.coarse)) || (/prefers-color-scheme:\s*dark/.test(q) && win.__osDark); }, media:q, addListener(){}, removeListener(){}, addEventListener(){}, removeEventListener(){} });
  if(opts && opts.coarse){ Object.defineProperty(win, 'innerWidth', { value: 390, configurable:true }); }
  win.eval(scripts.join('\n;\n') + `;window.__X = s => eval(s);`);
  return win;
}
const R = []; const P = (n, ok, note) => R.push({ n, ok, note: String(note||'') });
const win = boot({ coarse:true });
const X = s => win.__X(s);
const tryX = s => { try { return X(s); } catch(e){ return 'ERR ' + e.message; } };
(async () => {
try {
  X(`seedDemoData(); SESSION.loggedIn=true; SESSION.role='operator'; SESSION.user='홍길동'; SESSION.userId='U-OP';`);
  X(`SES.set({shift:{code:'day',name:'주간'}, worker:{id:'W1',name:'홍길동',emp_no:'OP-014'}, equipment: buildEquipmentList().find(e=>e.proc==='FORGE'), started:Date.now()});`);
  const eqName = X(`SES.get().equipment.name`);
  // 1 진입 규칙 — ★ v0.37.2 역할 기반 (기기 추측 제거): worker → 현장 · operator/manager → PC · 수동 「현장 모드」(vela_ui_mode='mobile') 만 예외
  P('1 진입(v0.37.2 역할 기반): worker → 현장 · operator(coarse 폰이어도) → PC · manager → PC · 수동 켜기(vela_ui_mode=mobile) 만 예외 · worker 는 vela_ui_mode=pc 무시', X(`localStorage.removeItem('vela_ui_mode'); SESSION.role='worker'; const a = mobileEntryDefault(); SESSION.role='operator'; const b = mobileEntryDefault(); SESSION.role='manager'; const c = mobileEntryDefault(); localStorage.setItem('vela_ui_mode','mobile'); SESSION.role='operator'; const d = mobileEntryDefault(); localStorage.setItem('vela_ui_mode','pc'); SESSION.role='worker'; const e = mobileEntryDefault(); SESSION.role='operator'; localStorage.removeItem('vela_ui_mode'); a===true && b===false && c===false && d===true && e===true`), '');
  // 2 내 작업 = 설비 세션 기준
  const jobsInfo = X(`(()=>{ const j = mobileJobs(SES.get()); const allOk = j.jobs.every(x => x.avail > 0 && LOT.balance(x.plot_no, x.proc) === x.avail && !lotHoldInfo(x.plot_no).held); const mine = j.jobs.every(x => { const wo = DB.query('work_orders', w => w.plot_no === x.plot_no)[0]; const pl = DB.all('production_plans').some(p => p.wo_id === wo?.id && p.equipment === '${eqName}'); return pl || (wo && Object.values(wo.plan_eq||{}).includes('${eqName}')); }); return { n: j.jobs.length, allOk, mine, first: j.jobs[0] && j.jobs[0].plot_no }; })()`);
  P('2 M01 내 작업 = 내 설비(계획 레인/WO 계획 설비) ∧ balance>0 ∧ HOLD 아님 · 「지금 할 작업」 = 첫 항목', jobsInfo.n > 0 && jobsInfo.allOk && jobsInfo.mine, JSON.stringify(jobsInfo));
  // 다른 설비 세션이면 목록이 달라진다 (작업자 개인이 아니라 설비 기준)
  const otherN = X(`(()=>{ const s = SES.get(); const other = buildEquipmentList().find(e => e.proc === 'CUT'); const j = mobileJobs({ ...s, equipment: other }); return j.jobs.map(x=>x.plot_no).filter(p => mobileJobs(s).jobs.some(y => y.plot_no === p)).length; })()`);
  P('2b 설비를 바꾸면 내 작업이 바뀐다 (절단기 세션과 프레스 세션의 작업 겹침 0 · 작업자 동일)', otherN === 0, 'overlap ' + otherN);
  // 3 M02 필드 실제값 · 계산 신설 0
  const first = jobsInfo.first;
  X(`location.hash = '#m/home'; router();`);
  P('3 M01 렌더(v0.37.3 작업 순서): ● 진행 카드 · 순번 ①~ · ○ 대기 · 하단 4탭 · PC 메뉴 숨김(m-mode) · 라벨 「작업 가능」 · [■ 정지] · [수동] 0', X(`(()=>{ const now = document.querySelector('.m-seq-it.now'); const nos = [...document.querySelectorAll('.m-seq-no')].map(e => +e.textContent); return !!now && document.querySelectorAll('.m-tabs a').length === 4 && document.getElementById('app').classList.contains('m-mode') && /작업 가능/.test(now.textContent) && !/acceptedGood|pendingQty/.test(document.getElementById('view').textContent) && nos.length >= 2 && nos.every((n,i) => n === i+1) && document.querySelectorAll('.m-seq-it.wait').length === nos.length - 1 && !!document.getElementById('m-stop') && !document.getElementById('btn-manual'); })()`), '');
  X(`location.hash = '#m/job/${first}/FORGE'; router();`);
  P('3b M02 상세 = balance 실제값 · 지시수량 = WO.qty · 계산 신설 0 (소스: mobile 코드에 Math/reduce 로 수량 계산 없음 — 헬퍼 호출만)', X(`(()=>{ const t = document.querySelector('.m-kv.big').textContent.replace(/,/g,''); const bal = LOT.balance('${first}','FORGE'); const src = String(VIEWS.m_job) + String(VIEWS.m_home) + String(mobileJobs); return t.includes(String(bal)) && !/totalGood\\(|good\\s*[-+]|\\.reduce\\((s,\\s*r)\\s*=>\\s*s\\s*\\+\\s*\\(?r\\.good/.test(src); })()`), '');
  // 4 M03 저장 = registerRecord 1회 · payload 세션값 · ★ v0.37.3 잔량 > 0 → 현재 작업 유지(토스트 · 입력 초기화) · [다음 작업으로] 링크(실적 0)
  const before = X(`DB.all('records').length`);
  X(`location.hash = '#m/run/${first}/FORGE'; router(); document.querySelector('[data-key="1"]').onclick(); document.querySelector('[data-key="5"]').onclick(); window.__calls = 0; const _o = LOT.registerRecord; LOT.registerRecord = function(p){ window.__calls++; window.__p = p; return _o.call(LOT, p); }; document.getElementById('m-done').onclick(); LOT.registerRecord = _o;`);
  const p4 = X(`window.__p`);
  P('4 M03 완료 = LOT.registerRecord 1회 · payload = 세션 worker/equipment/shift · records +1 · 잔량 > 0 → 같은 작업 화면 유지 + 수량 0 초기화 (완료 화면 없음)', X(`window.__calls`) === 1 && p4.good === 15 && p4.worker?.name === '홍길동' && p4.equipment === eqName && p4.shift === 'day' && X(`DB.all('records').length`) === before + 1 && X(`location.hash`) === `#m/run/${first}/FORGE` && X(`document.querySelector('.qval-big').textContent`) === '0', JSON.stringify(p4));
  const s4b = X(`(()=>{ const cur = SES.get().current; const skip = document.getElementById('m-skip'); const n0 = DB.all('records').length; const href = skip && skip.getAttribute('href'); if(skip) skip.onclick(); location.hash = href; router(); const moved = location.hash === href && location.hash !== '#m/run/${first}/FORGE'; const cur2 = SES.get().current; location.hash = '#m/home'; router(); const seqTxt = document.querySelector('.m-seq').textContent; const firstWait = !!document.querySelector('.m-seq-it.wait[href*="${first}"]'); return { curOk: cur && cur.plot_no === '${first}', hadSkip: !!skip, moved, added: DB.all('records').length - n0, cur2: cur2 && cur2.plot_no, firstWait, nowIsOther: !document.querySelector('.m-seq-it.now') || !/${first}/.test(document.querySelector('.m-seq-it.now').textContent) }; })()`);
  P('4b [다음 작업으로] = 화면 이동만(실적 0) · 이동 후 ● = 다음 작업 · 잔량 남은 첫 작업은 ○ 미완료로 표시', s4b.curOk && s4b.hadSkip && s4b.moved && s4b.added === 0 && s4b.cur2 !== first && s4b.firstWait && s4b.nowIsOther, JSON.stringify(s4b));
  X(`SES.setCurrent({ plot_no:'${first}', proc:'FORGE' });`);
  // 5 초과 입력 → 차단 · 입력값 유지 · 배너
  const bal5 = X(`LOT.balance('${first}','FORGE')`);
  X(`location.hash = '#m/run/${first}/FORGE'; router(); sessionStorage.removeItem('vela_m_draft'); router(); ['9','9','9','9'].forEach(k => document.querySelector('[data-key="'+k+'"]').onclick()); document.getElementById('m-done').onclick();`);
  P('5 초과 입력 9999 → write path 차단(초과 등록 차단) · 입력값 유지 · 빨간 배너 · records 불변', X(`/초과 등록 차단/.test(document.querySelector('.m-ban.red')?.textContent||'') && document.querySelector('.qval-big').textContent === '9999'`) && X(`DB.all('records').length`) === before + 1, 'bal ' + bal5);
  X(`sessionStorage.removeItem('vela_m_draft');`);
  // 6 M04: 앞 공정 완료 → 다음 공정 설비 세션의 내 작업에 노출 · 실적 자동 생성 0
  const m04 = X(`(()=>{ const heat = DB.all('material_lots')[0]?.heat || 'H2604-101'; LOT.create({ plot_no:'PL-M-1', itemCode:'HF-3301', materialLots:[heat], qty_initial:100 }); DB.set('work_orders','WO-M-1',{ id:'WO-M-1', itemCode:'HF-3301', plot_no:'PL-M-1', qty:100, so_id:null, plan_eq:{ CUT:'절단기 1호', FORGE:'프레스 1호' }, created:Date.now() }); const cutS = { ...SES.get(), equipment: buildEquipmentList().find(e => e.name === '절단기 1호') }; const forgeS = SES.get(); const b0 = mobileJobs(forgeS).jobs.some(j => j.plot_no === 'PL-M-1'); const c0 = mobileJobs(cutS).jobs.some(j => j.plot_no === 'PL-M-1'); const n0 = DB.all('records').length; LOT.registerRecord({ plot_no:'PL-M-1', proc:'CUT', equipment:'절단기 1호', good:100, type:'in', shift:'day' }); const b1 = mobileJobs(forgeS).jobs.some(j => j.plot_no === 'PL-M-1' && j.avail === 100); const c1 = mobileJobs(cutS).jobs.some(j => j.plot_no === 'PL-M-1'); return { b0, c0, b1, c1, added: DB.all('records').length - n0, forgeRecs: DB.query('records', r => r.plot_no==='PL-M-1' && r.proc==='FORGE').length }; })()`);
  P('6 M04: 절단 전 프레스 세션에 없음 → 절단 100 완료 → 프레스 세션 「내 작업」 에 작업 가능 100 자동 노출 · 절단 세션에서는 사라짐 · 단조 실적 자동 생성 0', m04.b0 === false && m04.c0 === true && m04.b1 === true && m04.c1 === false && m04.added === 1 && m04.forgeRecs === 0, JSON.stringify(m04));
  // 7 Q6-0 시나리오 A: 150+150 / 200
  const sA = X(`(()=>{ const heat = DB.all('material_lots')[0]?.heat || 'H2604-101'; LOT.create({ plot_no:'PL-M-A', itemCode:'HF-3301', materialLots:[heat], qty_initial:200 }); DB.set('work_orders','WO-M-A',{ id:'WO-M-A', itemCode:'HF-3301', plot_no:'PL-M-A', qty:200, so_id:null, plan_eq:{ FORGE:'프레스 1호', HEAT:'외주' }, created:Date.now() }); LOT.registerRecord({ plot_no:'PL-M-A', proc:'CUT', equipment:'절단기 1호', good:200, type:'in', shift:'day' }); LOT.registerRecord({ plot_no:'PL-M-A', proc:'FORGE', equipment:'프레스 1호', good:150, type:'in', shift:'day', worker:{name:'A'} }); DB.set('records','R-M-B',{ id:'R-M-B', plot_no:'PL-M-A', proc:'FORGE', type:'in', good:150, defect:0, rework:0, scrap:0, rework_returned:0, ts:Date.now()+5000, by:'B' }); location.hash='#m/job/PL-M-A/FORGE'; router(); const t = document.getElementById('view').textContent.replace(/\\s+/g,' '); return { pend: LOT.pendingQty('PL-M-A','FORGE'), acc: LOT.acceptedGood('PL-M-A','FORGE'), bal: LOT.balance('PL-M-A','FORGE'), banner: /확인 필요 100 EA/.test(t), reported: /보고 300 EA/.test(t), noInternal: !/acceptedGood|pending/.test(t) }; })()`);
  P('7 Q6-0 A: 단조 150+150/200 → 인정 200 · 확인 필요 100 · 배너 「확인 필요 100 EA · 관리자 판정」 + 「보고 300」 · 내부 용어 0 · PC 값과 동일', sA.pend === 100 && sA.acc === 200 && sA.bal === 0 && sA.banner && sA.reported && sA.noInternal, JSON.stringify(sA));
  // 8 시나리오 B: 하류 250 선등록 → 작업 가능 250 아님
  const sB = X(`(()=>{ DB.set('records','R-M-H',{ id:'R-M-H', plot_no:'PL-M-A', proc:'HEAT', type:'out', vendor:'V', good:250, defect:0, rework:0, scrap:0, rework_returned:0, ts:Date.now()+9000, by:'H' }); const s = { ...SES.get(), equipment: { id:'E-SHOT', name:'쇼트 1호', proc:'SHOT' } }; DB.set('work_orders','WO-M-A',{ plan_eq:{ FORGE:'프레스 1호', HEAT:'외주', SHOT:'쇼트 1호' } }); const j = mobileJobs(s).jobs.find(x => x.plot_no === 'PL-M-A'); return { avail: j && j.avail, heatPend: LOT.pendingQty('PL-M-A','HEAT'), heatAcc: LOT.acceptedGood('PL-M-A','HEAT') }; })()`);
  P('8 Q6-0 B: 열처리 250 선등록 → 쇼트 세션 작업 가능 = 200 (250 아님 · 인정 기준) · 열처리 확인 필요 50', sB.avail === 200 && sB.heatPend === 50 && sB.heatAcc === 200, JSON.stringify(sB));
  // 9 시나리오 C: 상류 보정 후 재조회 값 변경 · stale 화면값으로 초과 저장 불가
  const sC = X(`(()=>{ location.hash='#m/run/PL-M-A/FORGE'; router(); sessionStorage.removeItem('vela_m_draft'); router(); const shown0 = document.querySelector('.bal-big .bv').textContent; const recA = DB.query('records', r => r.plot_no==='PL-M-A' && r.proc==='FORGE' && r.worker?.name==='A')[0]; LOT.correctRecord(recA.id, { good:50, defect:0, rework:0 }, 'Case A'); const pendAfter = LOT.pendingQty('PL-M-A','FORGE'); const balAfter = LOT.balance('PL-M-A','FORGE'); ['5','0'].forEach(k => document.querySelector('[data-key="'+k+'"]').onclick()); const n0 = DB.all('records').length; document.getElementById('m-done').onclick(); const blocked = DB.all('records').length === n0 && /초과 등록 차단/.test(document.querySelector('.m-ban.red')?.textContent||''); router(); const shown1 = document.querySelector('.bal-big .bv').textContent; return { shown0, pendAfter, balAfter, blocked, shown1 }; })()`);
  P('9 Q6-0 C: 화면이 잔량 0 이던 상태에서 상류 보정(A 150→50) → 보류 0 · 잔량 0(A50+B150=200) · 이전 화면값 무관하게 50 등록은 write path 가 현재 원장으로 차단 · 재조회 값 갱신', sC.pendAfter === 0 && sC.balAfter === 0 && sC.blocked === true, JSON.stringify(sC));
  X(`sessionStorage.removeItem('vela_m_draft');`);
  // 10 M06 HOLD → 작업 시작 비활성 + write path 차단 · NC 판정 대기 → 가능 + 배너
  const s10 = X(`(()=>{ const dt = DB.all('defect_types').find(d => d.active !== false).code; const nc = qcRegisterNc({ lot_id:'PL-M-1', item_code:'HF-3301', defect_type: dt, qty: 2, hold:true, hold_reason:'검증' }); location.hash='#m/job/PL-M-1/FORGE'; router(); const btnDisabled = !!document.querySelector('button.m-btn.primary[disabled]') && /HOLD/.test(document.querySelector('button.m-btn.primary[disabled]').textContent); const banner = /품질 HOLD/.test(document.getElementById('view').textContent); let blocked = false; try { LOT.registerRecord({ plot_no:'PL-M-1', proc:'FORGE', equipment:'프레스 1호', good:1, type:'in', shift:'day' }); } catch(e){ blocked = /HOLD/.test(e.message); } const inJobs = mobileJobs(SES.get()).jobs.some(j => j.plot_no === 'PL-M-1'); const inAttn = mobileJobs(SES.get()).attention.some(j => j.plot_no === 'PL-M-1' && j.held); ncSetHold(nc.id, false, '해제'); location.hash='#m/job/PL-M-1/FORGE'; router(); const pendBanner = /품질 판정 대기/.test(document.getElementById('view').textContent); const startOk = !!document.querySelector('a.m-btn.primary'); const inJobs2 = mobileJobs(SES.get()).jobs.some(j => j.plot_no === 'PL-M-1'); return { btnDisabled, banner, blocked, inJobs, inAttn, pendBanner, startOk, inJobs2 }; })()`);
  P('10 M06: HOLD → [작업 시작] 비활성 + 배너 + registerRecord 차단 + 내 작업 제외·확인 필요 포함 → HOLD 해제(판정 대기) → 배너 「품질 판정 대기」 + 작업 시작 가능 + 내 작업 복귀', s10.btnDisabled && s10.banner && s10.blocked && !s10.inJobs && s10.inAttn && s10.pendBanner && s10.startOk && s10.inJobs2, JSON.stringify(s10));
  // 11 권한: operator 가 #audit/#set 직접 이동 → 기존 가드 · scan 권한 none → 현장 모드 불가
  const s11 = X(`(()=>{ location.hash='#audit'; router(); const a = location.hash === '#dash'; location.hash='#set'; router(); const b = location.hash === '#dash'; const _g = getUserPerm; window.getUserPerm = (u, id) => id === 'scan' ? 'none' : _g(u, id); location.hash='#m/home'; router(); const c = location.hash === '#dash' && !document.getElementById('app').classList.contains('m-mode'); window.getUserPerm = _g; return { a, b, c }; })()`);
  P('11 권한: operator #audit/#set 직접 이동 → #dash 로 차단(기존 가드) · scan 권한 none → 현장 모드 진입 거부', s11.a && s11.b && s11.c, JSON.stringify(s11));
  // 12 새로고침·뒤로가기 무손실: 입력 draft sessionStorage 보존 · 세션 유지
  const s12 = X(`(()=>{ location.hash='#m/run/PL-M-1/FORGE'; router(); sessionStorage.removeItem('vela_m_draft'); router(); ['7','7'].forEach(k => document.querySelector('[data-key="'+k+'"]').onclick()); router(); const kept = document.querySelector('.qval-big').textContent === '77'; location.hash='#m/job/PL-M-1/FORGE'; router(); location.hash='#m/run/PL-M-1/FORGE'; router(); const kept2 = document.querySelector('.qval-big').textContent === '77'; sessionStorage.removeItem('vela_m_draft'); return { kept, kept2, sess: !!SES.get() }; })()`);
  P('12 새로고침(재렌더)·뒤로가기 후 입력값 77 유지 (sessionStorage 단말 전용) · 세션 유지', s12.kept && s12.kept2 && s12.sess, JSON.stringify(s12));
  // 13 PC ↔ Mobile 동일 원장 (별도 인스턴스 = PC 화면 · 같은 localStorage 스냅샷)
  const snap = X(`JSON.stringify(DB.snapshot())`);
  const pc = boot({ coarse:false });
  pc.__SNAP = snap;
  const pcVals = pc.__X(`(()=>{ DB.restore(JSON.parse(window.__SNAP)); SESSION.loggedIn=true; SESSION.role='manager'; SESSION.user='qa'; return { bal: LOT.balance('PL-M-A','SHOT'), pend: LOT.pendingQty('PL-M-A','FORGE'), hpend: LOT.pendingQty('PL-M-A','HEAT'), held: lotHoldInfo('PL-M-1').held, ncPend: lotPendingInfo('PL-M-1').pending.length, entry: mobileEntryDefault() }; })()`);
  const mVals = X(`({ bal: mobileJobs({ ...SES.get(), equipment:{ id:'E-SHOT', name:'쇼트 1호', proc:'SHOT' } }).jobs.find(j => j.plot_no==='PL-M-A').avail, pend: LOT.pendingQty('PL-M-A','FORGE'), hpend: LOT.pendingQty('PL-M-A','HEAT'), held: lotHoldInfo('PL-M-1').held, ncPend: lotPendingInfo('PL-M-1').pending.length })`);
  P('13 PC ↔ Mobile 동일 원장: 별도 PC 인스턴스(manager · 마우스)에서 balance/pending/HOLD/NC 값 일치 · PC 인스턴스는 자동 진입 안 함', pcVals.bal === mVals.bal && pcVals.pend === mVals.pend && pcVals.hpend === mVals.hpend && pcVals.held === mVals.held && pcVals.ncPend === mVals.ncPend && pcVals.entry === false, JSON.stringify({ pcVals, mVals }));
  // 14 PC 화면 무변: m-mode 해제 시 nav 복귀 · PC 라우트 정상 · 모바일 전용 DB.set 0
  const s14 = X(`(()=>{ location.hash='#m/more'; router(); document.getElementById('m-pc').onclick(); router(); const a = !document.getElementById('app').classList.contains('m-mode') && document.getElementById('nav').children.length > 0 && location.hash === '#dash'; const src = [mobileJobs, mobileStatusBanners, mobileRouter, VIEWS.m_home, VIEWS.m_job, VIEWS.m_run, VIEWS.m_done, VIEWS.m_check, VIEWS.m_more, VIEWS.m_clockin, mobileClockOut, resolveScanEquipment, matchEquipmentQr, SES.clockIn, SES.setEquipment, SES.clockOut].map(String).join(''); const noWrite = !/DB\\.set\\(|DB\\.correct\\(|voidDoc\\(/.test(src); return { a, noWrite }; })()`);
  P('14 PC 복귀 정상(nav·#dash) · 모바일 코드에 DB.set/correct/void 0 (쓰기는 registerRecord 만) · 로컬 키 vela_ui_mode 는 DB 밖', s14.a && s14.noWrite && X(`localStorage.getItem('vela_ui_mode')`) === 'pc', JSON.stringify(s14));
  // 15 화면 모드: 폰 기본 = 기기(OS) 설정 따름(auto) · 더보기 선택칸 · PC 기본 라이트
  const t15 = X(`(()=>{ localStorage.removeItem('vela_theme'); const prefPhone = getThemePref(); window.__osDark = true; applyTheme('auto'); const darkNow = getTheme(); window.__osDark = false; applyTheme('auto'); const lightNow = getTheme(); location.hash='#m/more'; router(); const seg = document.querySelectorAll('[data-theme-pick]').length; const onAuto = document.querySelector('[data-theme-pick="auto"]').classList.contains('on'); document.querySelector('[data-theme-pick="dark"]').onclick(); const pickDark = getTheme() === 'dark' && localStorage.getItem('vela_theme') === 'dark' && document.querySelector('[data-theme-pick="dark"]').classList.contains('on'); window.__osDark = true; const stillDark = resolveTheme(getThemePref()) === 'dark'; document.querySelector('[data-theme-pick="light"]').onclick(); const pickLight = getTheme() === 'light' && stillDark; document.querySelector('[data-theme-pick="auto"]').onclick(); const backAuto = getTheme() === 'dark' && localStorage.getItem('vela_theme') === 'auto'; localStorage.removeItem('vela_theme'); window.__osDark = false; applyTheme(getThemePref()); return { prefPhone, darkNow, lightNow, seg, onAuto, pickDark, pickLight, backAuto }; })()`);
  P('15 화면 모드: 폰 기본 auto(기기 설정) · OS 다크→다크/라이트→라이트 · 더보기 3버튼(자동/밝게/어둡게) · 선택 저장(vela_theme) · 자동 복귀 시 OS 값', t15.prefPhone === 'auto' && t15.darkNow === 'dark' && t15.lightNow === 'light' && t15.seg === 3 && t15.onAuto && t15.pickDark && t15.pickLight && t15.backAuto, JSON.stringify(t15));
  const pcT = boot({ coarse:false, osDark:true });
  P('15b PC(마우스) 기본 테마 = 라이트 유지 (OS 다크여도 · v0.32.0 사용자 판정) · 설정 라디오 3개', pcT.__X(`localStorage.removeItem('vela_theme'); getThemePref()`) === 'light' && pcT.__X(`resolveTheme(getThemePref())`) === 'light', pcT.__X(`getThemePref()`));
  /* ================= ★ v0.37.2 — SPEC v0.2 (GPT 피드백 2026-09-13 §15) ================= */
  // 16 세션 저장 = 단말 로컬 · settings/active_session 읽기·쓰기 0 · 사용자 바뀌면 상속 0
  const s16 = X(`(()=>{ const _g = DB.get, _s = DB.set; let hits = 0; DB.get = function(c,i){ if(c==='settings' && i==='active_session') hits++; return _g.call(DB,c,i); }; DB.set = function(c,i,d){ if(c==='settings' && i==='active_session') hits++; return _s.call(DB,c,i,d); }; SES.clockOut(); const s0 = SES.get(); SES.clockIn({ shift:{code:'day',name:'주간'}, worker:{id:'OP-014',name:'홍길동',emp_no:'OP-014'} }); const s1 = SES.get(); SES.setEquipment({ id:'E1', name:'프레스 1호', proc:'FORGE' }); const s2 = SES.get(); DB.get = _g; DB.set = _s; const raw = localStorage.getItem('vela_m_session'); const inDb = !!DB.get('settings','active_session'); const uid = SESSION.userId; SESSION.userId = 'U-OTHER'; const other = SES.get(); SESSION.userId = uid; const back = SES.get(); const noSrc = !/active_session/.test(String(SES.get) + String(SES.set) + String(SES.clockIn)); return { hits, s0, s1ok: !!s1 && s1.worker.id==='OP-014' && s1.equipment===null && s1.userId==='U-OP', s2eq: s2 && s2.equipment && s2.equipment.name, raw: !!raw && /"userId":"U-OP"/.test(raw), inDb, other, backOk: !!back, noSrc }; })()`);
  P('16 세션 = 단말 로컬(vela_m_session · userId 포함) · settings/active_session 읽기·쓰기 0(DB 스파이) · 원장 스냅샷에 세션 문서 0 · 다른 사용자로 바뀌면 SES.get()=null(상속 0) · 원 사용자 복귀 시 유지', s16.hits === 0 && s16.s0 === null && s16.s1ok && s16.s2eq === '프레스 1호' && s16.raw && !s16.inDb && s16.other === null && s16.backOk && s16.noSrc, JSON.stringify(s16));
  // 16b 폰 A / 폰 B 격리 — 별도 인스턴스(별도 localStorage) · A 출근 후 B 출근 → A 세션 불변
  const phoneB = boot({ coarse:true });
  phoneB.__X(`seedDemoData(); SESSION.loggedIn=true; SESSION.role='worker'; SESSION.user='이영호'; SESSION.userId='U-B'; SES.clockIn({ shift:{code:'night',name:'야간'}, worker:{id:'OP-021',name:'이영호'} }); SES.setEquipment({ id:'E2', name:'절단기 1호', proc:'CUT' });`);
  const s16b = { a: X(`(()=>{ const s = SES.get(); return { w: s.worker.name, eq: s.equipment && s.equipment.name, sh: s.shift.code }; })()`), b: phoneB.__X(`(()=>{ const s = SES.get(); return { w: s.worker.name, eq: s.equipment && s.equipment.name, sh: s.shift.code }; })()`) };
  P('16b 폰 A(홍길동·프레스 1호·주간) 출근 → 폰 B(이영호·절단기 1호·야간) 출근 → A 세션·설비 불변 · B 도 자기 것 (전역 문서 없음)', s16b.a.w === '홍길동' && s16b.a.eq === '프레스 1호' && s16b.a.sh === 'day' && s16b.b.w === '이영호' && s16b.b.eq === '절단기 1호' && s16b.b.sh === 'night', JSON.stringify(s16b));
  // 17 ★ v0.37.4 — 설비 = 목록 선택만 · 조회 탭 = 읽기 전용 · QR 입력 경로 0
  const s17 = X(`(()=>{ SES.clockOut(); SES.clockIn({ shift:{code:'day',name:'주간'}, worker:{id:'OP-014',name:'홍길동',emp_no:'OP-014'} }); const j0 = mobileJobs(SES.get()).jobs.length; location.hash='#m/home'; router(); const v = document.getElementById('view'); const noeq = !!document.querySelector('.m-noeq') && !!document.getElementById('m-eq-pick') && !v.querySelector('a[href="#m/scan"], a[href="#m/trace"].m-btn'); const noQrWord = !/QR 스캔/.test(v.textContent); document.getElementById('m-eq-pick').onclick(); const modalNoQr = !document.querySelector('#modal a[href="#m/scan"]') && !/QR/.test(document.getElementById('modal').textContent); const items = [...document.querySelectorAll('#modal [data-eq]')].map(b => b.dataset.eq); const master = buildEquipmentList().map(e => e.name); const fromMaster = items.length > 0 && items.every(n => master.includes(n)); document.querySelector('#modal [data-eq="프레스 1호"]').onclick(); const eq1 = SES.get().equipment && SES.get().equipment.name; const j1 = mobileJobs(SES.get()).jobs; const j1ok = j1.length > 0 && j1.every(j => LOT.balance(j.plot_no, j.proc) === j.avail); const tabs = [...document.querySelectorAll('.m-tabs a')].map(a => a.getAttribute('href') + ':' + a.textContent.trim()); const tabOk = tabs.some(t => t.startsWith('#m/trace:') && /조회/.test(t)) && !tabs.some(t => /QR 스캔/.test(t)); return { j0, noeq, noQrWord, modalNoQr, fromMaster, eq1, j1n: j1.length, j1ok, tabOk, tabs: tabs.join('|') }; })()`);
  P('17 v0.37.4 설비 = 목록만: 출근 직후 작업 0 · 설비 없음 화면 = [설비 선택] 하나(QR 버튼·문구 0) · 선택 창 = 설비 마스터 목록(QR 링크 0) → 프레스 1호 → 작업 순서(balance 동일) · 하단 탭 「조회」(QR 스캔 탭 0)', s17.j0 === 0 && s17.noeq && s17.noQrWord && s17.modalNoQr && s17.fromMaster && s17.eq1 === '프레스 1호' && s17.j1ok && s17.tabOk, JSON.stringify(s17));
  // 17b 조회 탭 = 읽기 전용 (DB 스파이 0) · LOT QR/작업지시 QR/포장 QR → LOT 이력 · 값 = Core · 설비 QR → 설비 정보 · 실적 등록 버튼 0 · 모르는 QR → 안내
  const s17b = X(`(()=>{ const _s = DB.set, _c = DB.correct, _v = DB.void; let w = 0; DB.set = function(){ w++; return _s.apply(DB, arguments); }; if(_c) DB.correct = function(){ w++; return _c.apply(DB, arguments); }; if(_v) DB.void = function(){ w++; return _v.apply(DB, arguments); }; location.hash='#m/trace'; router(); const cam = !!document.getElementById('m-tr-q'); VIEWS._traceLookup(JSON.stringify({ plot_no:'PL-M-A', item:'HF-3301', wo:'WO-M-A' })); const t1 = document.getElementById('view').textContent; const lotShown = /PL-M-A/.test(t1) && /공정 이력/.test(t1); const good = LOT.totalGood('PL-M-A','FORGE'); const pend = LOT.pendingQty('PL-M-A','FORGE'); const valOk = new RegExp('보고 ' + good.toLocaleString()).test(t1.replace(/\\s+/g,' ')) && (pend ? new RegExp('확인 필요 ' + pend.toLocaleString()).test(t1.replace(/\\s+/g,' ')) : true); const noRegBtn = !document.querySelector('#view a[href^="#m/run/"], #view a[href^="#m/job/"]') && !/실적 등록|작업 시작/.test(t1); VIEWS._traceLookup(JSON.stringify({ plot_no:'PL-M-1', item:'HF-3301', pack_qty:50 })); const packOk = /PL-M-1/.test(document.getElementById('view').textContent); VIEWS._traceLookup('EQ-CUT-1'); const eqOk = /절단기 1호/.test(document.getElementById('view').textContent) && /오늘 실적/.test(document.getElementById('view').textContent); VIEWS._traceLookup('없는QR'); const errOk = /인식할 수 없는/.test(document.getElementById('view').textContent); VIEWS._traceLookup('PL-M-A'); const typedOk = /PL-M-A/.test(document.getElementById('view').textContent); DB.set = _s; if(_c) DB.correct = _c; if(_v) DB.void = _v; const src = String(VIEWS.m_trace); const noWriteSrc = !/DB\\.set\\(|DB\\.correct\\(|voidDoc\\(|registerRecord\\(/.test(src); return { cam, lotShown, valOk, noRegBtn, packOk, eqOk, errOk, typedOk, writes: w, noWriteSrc }; })()`);
  P('17b 조회 = 읽기 전용: 작업지시 QR → LOT 이력(공정 이력 값 = Core totalGood/pendingQty) · 실적 등록/작업 시작 버튼 0 · 포장 QR → 같은 LOT · 설비 QR → 설비 정보(오늘 실적) · 모르는 QR → 안내 · LOT 번호 입력 조회 · DB 쓰기 0(스파이) · 소스에 write path 0', s17b.cam && s17b.lotShown && s17b.valOk && s17b.noRegBtn && s17b.packOk && s17b.eqOk && s17b.errOk && s17b.typedOk && s17b.writes === 0 && s17b.noWriteSrc, JSON.stringify(s17b));
  // 18 교대 자동 판정 · 수동 변경 · payload.shift 반영 · records.shift 무변
  const s18 = X(`(()=>{ const at = h => shiftAt(new Date(2026,8,13,h,0,0).getTime()).code; const auto = { h9: at(9), h22: at(22), h3: at(3), h7: at(7), h8: at(8), h19: at(19), h20: at(20) }; location.hash='#m/more'; router(); const chips = document.querySelectorAll('[data-shift-pick]').length; document.querySelector('[data-shift-pick="night"]').onclick(); const sh = SES.get().shift.code; const p = buildPhonePayload(SES.get(), { plot_no:'PL-M-1', proc:'FORGE', item:'HF-3301' }, 'good', 1, ''); document.querySelector('[data-shift-pick="day"]').onclick(); const back = SES.get().shift.code; const recShiftKept = DB.all('records').every(r => r.shift === undefined || typeof r.shift === 'string'); return { auto, chips, sh, pShift: p.shift, back, recShiftKept }; })()`);
  P('18 교대: 09→day · 22→night · 03→night(자정 넘김) · 07→night · 08→day · 19→day · 20→night · 더보기 칩 2개 · 야간 탭 → 세션 shift=night → payload.shift=night · 주간 복귀 · records.shift 구조 무변', s18.auto.h9 === 'day' && s18.auto.h22 === 'night' && s18.auto.h3 === 'night' && s18.auto.h7 === 'night' && s18.auto.h8 === 'day' && s18.auto.h19 === 'day' && s18.auto.h20 === 'night' && s18.chips === 2 && s18.sh === 'night' && s18.pShift === 'night' && s18.back === 'day' && s18.recShiftKept, JSON.stringify(s18));
  // 19 출근 화면: 이름 자동 매칭 · 교대 자동 선택 · 출근 → 세션(설비 null) → 홈 · 이름 불일치 → 작업자 목록 1탭
  const s19 = X(`(()=>{ SES.clockOut(); location.hash='#m/home'; router(); const clock = !!document.querySelector('.m-clock'); const nameOk = /홍길동/.test(document.querySelector('.m-clock-sub').textContent) && !document.querySelector('#view .m-list'); const autoChip = document.querySelector('.m-seg-btn.on') && document.querySelector('.m-seg-btn.on').dataset.sh === shiftAt(Date.now()).code; const tabs = document.querySelectorAll('.m-tabs a').length; document.getElementById('m-ci-go').onclick(); const s = SES.get(); const after = { hash: location.hash, w: s && s.worker.id, eq: s && s.equipment, sh: s && s.shift.code, started: s && typeof s.started === 'number' }; SES.clockOut(); const u = SESSION.user; SESSION.user = '없는사람'; location.hash='#m/home'; router(); const list = document.querySelectorAll('#view .m-list-it').length; const goDisabled = document.getElementById('m-ci-go').disabled; document.querySelector('#view .m-list-it[data-w="OP-008"]').onclick(); const picked = /김철수/.test(document.querySelector('.m-clock-sub').textContent) && !document.getElementById('m-ci-go').disabled; document.getElementById('m-ci-go').onclick(); const w2 = SES.get() && SES.get().worker.name; SESSION.user = u; SES.clockOut(); SES.clockIn({ shift:{code:'day',name:'주간'}, worker:{id:'OP-014',name:'홍길동',emp_no:'OP-014'} }); SES.setEquipment({ id:'E1', name:'프레스 1호', proc:'FORGE' }); return { clock, nameOk, autoChip, tabs, after, list, goDisabled, picked, w2 }; })()`);
  P('19 출근 화면: 로그인 이름 = 작업자 마스터 자동 매칭(목록 없음) · 교대 칩 = shiftAt(지금) · 하단 4탭 · [출근] → 세션(작업자 OP-014 · 설비 null · started) → #m/home · 이름 불일치 → 작업자 목록 1탭(선택 전 [출근] 비활성) → 김철수 선택 → 출근', s19.clock && s19.nameOk && s19.autoChip && s19.tabs === 4 && s19.after.hash === '#m/home' && s19.after.w === 'OP-014' && s19.after.eq === null && s19.after.sh === shiftNow(win) && s19.after.started && s19.list >= 5 && s19.goDisabled && s19.picked && s19.w2 === '김철수', JSON.stringify(s19));
  // 20 퇴근 = 세션 종료(근태 저장 0) → 출근 화면 · 실적 불변 · 로그인 유지
  const s20 = X(`(()=>{ const n0 = DB.all('records').length; const cols0 = Object.keys(DB.snapshot()).length; location.hash='#m/more'; router(); document.getElementById('m-clockout').onclick(); const modal = !!document.getElementById('m-co-ok'); document.getElementById('m-co-ok').onclick(); const gone = SES.get() === null; const clock = !!document.querySelector('.m-clock'); const n1 = DB.all('records').length; const cols1 = Object.keys(DB.snapshot()).length; const noAtt = !DB.snapshot().attendance && !DB.snapshot().clock_logs; return { modal, gone, clock, same: n0 === n1 && cols0 === cols1, noAtt, loggedIn: SESSION.loggedIn }; })()`);
  P('20 퇴근: 더보기 [퇴근·세션 종료] → 확인 → 세션 null → 출근 화면 · records 불변 · 근태 컬렉션 신설 0 · 로그인 유지', s20.modal && s20.gone && s20.clock && s20.same && s20.noAtt && s20.loggedIn, JSON.stringify(s20));
  // 21 역할 기반 진입 (enterAsUser) · 역할 변경 후 진입 변경 · worker 의 PC 해시 → 현장 · 더보기에 PC 버튼 0
  const s21 = X(`(()=>{ localStorage.removeItem('vela_ui_mode'); DB.set('users','U-OP',{ id:'U-OP', name:'홍길동', role:'operator', active:true }); location.hash='#dash'; enterAsUser(DB.get('users','U-OP')); const opHash = location.hash; DB.set('users','U-OP',{ role:'worker' }); location.hash='#dash'; enterAsUser(DB.get('users','U-OP')); const wHash = location.hash; const roleNow = SESSION.role; SES.clockIn({ shift:{code:'day',name:'주간'}, worker:{id:'OP-014',name:'홍길동',emp_no:'OP-014'} }); location.hash='#lot'; router(); const redirected = location.hash === '#m/home'; router(); location.hash='#m/more'; router(); const noPcBtn = !document.getElementById('m-pc'); const badge = document.getElementById('up-badge') && document.getElementById('up-badge').textContent; DB.set('users','U-OP',{ role:'manager' }); location.hash='#dash'; enterAsUser(DB.get('users','U-OP')); const mHash = location.hash; DB.set('users','U-OP',{ role:'operator' }); enterAsUser(DB.get('users','U-OP')); return { opHash, wHash, roleNow, redirected, noPcBtn, badge, mHash }; })()`);
  P('21 역할 진입: operator 로그인 → #dash · 역할을 worker 로 바꾸고 로그인 → #m/home · worker 가 #lot 직접 이동 → #m/home 으로 · 더보기에 「PC 화면으로」 0 · manager 로 바꾸면 #dash', s21.opHash === '#dash' && s21.wHash === '#m/home' && s21.roleNow === 'worker' && s21.redirected && s21.noPcBtn && s21.mHash === '#dash', JSON.stringify(s21));
  // 22 자동 로그인(기기 토큰): 발급 → 검증 진입 · 위조(userId 만) 불가 · 관리자 해제 · 역할 변경 · operator 발급 0 · 로컬에 비밀번호/해시 0 · 로그아웃 시 해제
  const s22 = await X(`(async()=>{ DB.set('users','U-W9',{ id:'U-W9', name:'테스트작업자', role:'worker', active:true, pin:'sha256:abc' }); const u = DB.get('users','U-W9'); const ok = await rememberLogin(u); const raw = localStorage.getItem('vela_remember'); const local = JSON.parse(raw); const dev = DB.get('users','U-W9').devices; const devN = Object.keys(dev).length; const hashOnServer = dev[local.dev].hash; const noSecret = !/sha256|abc|pin/.test(raw) && local.token !== hashOnServer && !('hash' in local); const v1 = await tryRememberedLogin(); localStorage.setItem('vela_remember', JSON.stringify({ userId:'U-W9', token:'forged', dev: local.dev })); const v2 = await tryRememberedLogin(); const cleared = localStorage.getItem('vela_remember') === null; localStorage.setItem('vela_remember', JSON.stringify({ userId:'U-W9', dev: local.dev })); const v2b = await tryRememberedLogin(); await rememberLogin(u); DB.set('users','U-W9',{ devices:{} }); const v3 = await tryRememberedLogin(); await rememberLogin(DB.get('users','U-W9')); DB.set('users','U-W9',{ role:'operator' }); const v4 = await tryRememberedLogin(); const opIssue = await rememberLogin(DB.get('users','U-W9')); DB.set('users','U-W9',{ role:'worker' }); await rememberLogin(DB.get('users','U-W9')); const before = !!localStorage.getItem('vela_remember'); const _rg = window.renderGate; window.renderGate = () => {}; doLogoutNow(); window.renderGate = _rg; const afterLogout = localStorage.getItem('vela_remember'); document.getElementById('pin-gate').classList.add('hide'); document.getElementById('app').style.display=''; SESSION.loggedIn=true; SESSION.role='operator'; SESSION.user='홍길동'; SESSION.userId='U-OP'; return { ok, devN, noSecret, v1: v1 && v1.id, v2, cleared, v2b, v3, v4, opIssue, before, afterLogout }; })()`);
  P('22 자동 로그인 B(기기 토큰): 발급 → users.devices 해시 1 · 로컬에 비밀번호/해시 0(토큰 ≠ 해시) → 검증 진입 U-W9 · 위조 토큰/userId 만 → 진입 불가 + 로컬 키 제거 · 관리자 [기기 해제] → 불가 · 역할 operator 로 바뀌면 불가 · operator 는 발급 0 · 로그아웃 시 로컬 해제', s22.ok === true && s22.devN === 1 && s22.noSecret && s22.v1 === 'U-W9' && s22.v2 === null && s22.cleared && s22.v2b === null && s22.v3 === null && s22.v4 === null && s22.opIssue === false && s22.before && s22.afterLogout === null, JSON.stringify(s22));
  // 22b 게이트에서 기억 진입: renderGate() → attemptRememberedLogin → 토큰 검증 후 enterAsUser → 현장 화면
  const s22b = await X(`(async()=>{ const u = DB.get('users','U-W9'); await rememberLogin(u); SESSION.loggedIn=false; SESSION.userId=null; SESSION.role=null; document.getElementById('pin-gate').classList.remove('hide'); location.hash='#dash'; renderGate(); const gateShown = !!document.getElementById('gt-name'); const rememberBox = !!document.getElementById('gt-remember'); await new Promise(r => setTimeout(r, 30)); const entered = SESSION.loggedIn && SESSION.userId === 'U-W9' && SESSION.role === 'worker' && location.hash === '#m/home' && document.getElementById('pin-gate').classList.contains('hide'); localStorage.removeItem('vela_remember'); SESSION.loggedIn=true; SESSION.role='operator'; SESSION.user='홍길동'; SESSION.userId='U-OP'; localStorage.removeItem('vela_ui_mode'); return { gateShown, rememberBox, entered }; })()`);
  P('22b 게이트 부팅: 기억된 기기 → renderGate 가 토큰 검증 후 자동 진입(U-W9 · worker · #m/home · 게이트 숨김) · 로그인 폼에 「이 기기에서 자동 로그인」 체크 존재', s22b.gateShown && s22b.rememberBox && s22b.entered, JSON.stringify(s22b));
  // 23 사용자 관리: 역할 3택 · worker 등록 · 배지 · [기기 해제]
  const s23 = X(`(()=>{ SESSION.role='manager'; location.hash='#masters'; router(); const setUsersTab = document.querySelector('[data-set-tab="users"], #set-tab-users, [data-tab="users"]'); if(setUsersTab && setUsersTab.onclick) setUsersTab.onclick(); const rows = document.getElementById('usr-rows'); const hasRows = !!rows; const badge = rows ? /현장 작업자/.test(rows.textContent) : false; const forget = rows ? !!rows.querySelector('[data-usr-forget="U-W9"]') : false; const addBtn = document.getElementById('usr-add'); if(addBtn) addBtn.onclick(); const radios = document.querySelectorAll('[name="ua-role"]').length; const radioVals = [...document.querySelectorAll('[name="ua-role"]')].map(r => r.value).join(','); document.getElementById('ua-name').value = '신규현장'; document.querySelector('[name="ua-role"][value="worker"]').checked = true; document.getElementById('ua-ok').onclick(); const nu = DB.all('users').find(u => u.name === '신규현장'); SESSION.role='operator'; location.hash='#m/home'; router(); return { hasRows, badge, forget, radios, radioVals, nuRole: nu && nu.role }; })()`);
  P('23 사용자 관리(관리자 · v0.38.16 기준정보 화면): 역할 라디오 3개(operator/worker/manager) · 「현장 작업자」 등록 → users.role=worker · 목록 배지 「현장 작업자」 · 기억 기기 있는 사용자에 [기기 해제] 버튼', s23.radios === 3 && s23.radioVals === 'operator,worker,manager' && s23.nuRole === 'worker' && s23.hasRows && s23.badge && s23.forget, JSON.stringify(s23));
  // 24 PC 실적 등록(VIEWS.scan) 무변: 로컬 세션(설비 null 허용) 으로도 스캔 화면 열림 · payload 설비는 기존 폴백
  const s24 = X(`(()=>{ localStorage.removeItem('vela_ui_mode'); SES.clockOut(); SES.clockIn({ shift:{code:'day',name:'주간'}, worker:{id:'OP-014',name:'홍길동',emp_no:'OP-014'} }); location.hash='#scan'; router(); const shell = !!document.querySelector('.scan-shell'); const noMode = !document.getElementById('app').classList.contains('m-mode'); const p = buildPhonePayload(SES.get(), { plot_no:'PL-M-1', proc:'FORGE', item:'HF-3301' }, 'good', 1, ''); SES.setEquipment({ id:'E1', name:'프레스 1호', proc:'FORGE' }); return { shell, noMode, eq: p.equipment, worker: p.worker && p.worker.id }; })()`);
  P('24 PC 실적 등록 무변: 설비 없는 로컬 세션으로도 #scan 열림(PC 모드) · payload 설비 = WO 계획 설비 폴백(프레스 1호) · worker 세션값', s24.shell && s24.noMode && s24.eq === '프레스 1호' && s24.worker === 'OP-014', JSON.stringify(s24));
  // 25 권한 보정: 현장 화면(#m/*) = scan 메뉴 권한 — scan 'view' 면 폰 실적 등록도 DB.set 가드가 차단 (v0.37.0 누락)
  const s25 = X(`(()=>{ DB.set('users','U-OP',{ perms:{ scan:'view' } }); location.hash='#m/run/PL-M-1/FORGE'; router(); const perm = currentPagePerm(); const n0 = DB.all('records').length; let msg = ''; try { LOT.registerRecord({ plot_no:'PL-M-1', proc:'FORGE', equipment:'프레스 1호', good:1, type:'in', shift:'day' }); } catch(e){ msg = e.message; } const n1 = DB.all('records').length; DB.set('users','U-OP',{ perms:{} }); location.hash='#m/home'; router(); const perm2 = currentPagePerm(); return { perm, blocked: n1 === n0, perm2 }; })()`);
  P('25 권한: 현장 화면 = 실적 등록(scan) 권한 적용 — scan=view 면 currentPagePerm=view · 폰 실적 등록 DB.set 차단(records 불변) · 권한 복구 시 edit', s25.perm === 'view' && s25.blocked && s25.perm2 === 'edit', JSON.stringify(s25));
  /* ================= ★ v0.37.3 — 작업 순서 · 완료 후 자동 이동 · 정지/설비 이동 (GPT 승인 2026-09-13 4문장) ================= */
  // 26 잔량 0 완료 → ✓ · 다음 순번 ● · 다음 작업 입력 화면 자동 이동(수량 빈 값) · 실적은 1건만(자동 실적 0)
  const s26 = X(`(()=>{ const heat = DB.all('material_lots')[0]?.heat || 'H2604-101'; LOT.create({ plot_no:'PL-M-S1', itemCode:'HF-3301', materialLots:[heat], qty_initial:20 }); DB.set('work_orders','WO-M-S1',{ id:'WO-M-S1', itemCode:'HF-3301', plot_no:'PL-M-S1', qty:20, so_id:null, plan_eq:{ CUT:'절단기 1호', FORGE:'프레스 1호' }, created:Date.now() }); LOT.registerRecord({ plot_no:'PL-M-S1', proc:'CUT', equipment:'절단기 1호', good:20, type:'in', shift:'day' }); SES.setEquipment({ id:'EQ-FORGE-1', name:'프레스 1호', proc:'FORGE' }); SES.setCurrent({ plot_no:'PL-M-S1', proc:'FORGE' }); location.hash='#m/home'; router(); const nowTxt = document.querySelector('.m-seq-it.now').textContent; const nowIsS1 = /PL-M-S1/.test(nowTxt); const seqBefore = [...document.querySelectorAll('.m-seq-it')].map(e => e.classList.contains('now') ? 'now' : e.classList.contains('done') ? 'done' : 'wait'); const jobsBefore = mobileJobs(SES.get()).jobs; const expectNext = mobileNextJob(SES.get(), jobsBefore.find(j => j.plot_no === 'PL-M-S1')); location.hash='#m/run/PL-M-S1/FORGE'; router(); sessionStorage.removeItem('vela_m_draft'); router(); ['2','0'].forEach(k => document.querySelector('[data-key="'+k+'"]').onclick()); const n0 = DB.all('records').length; document.getElementById('m-done').onclick(); const added = DB.all('records').length - n0; const hashAfter = location.hash; router(); const qvalEmpty = document.querySelector('.qval-big') && document.querySelector('.qval-big').textContent === '0'; const cur = SES.get().current; location.hash='#m/home'; router(); const doneRow = [...document.querySelectorAll('.m-seq-it.done')].find(e => /PL-M-S1/.test(e.textContent)); const doneIsS1 = !!doneRow && /✓/.test(doneRow.textContent) && /완료/.test(doneRow.textContent); const nowRow = document.querySelector('.m-seq-it.now'); const nowIsNext = !!nowRow && expectNext && nowRow.textContent.includes(expectNext.plot_no); const noDoneRoute = !VIEWS.m_done && !/#m\\/done/.test(String(VIEWS.m_run)); return { nowIsS1, seqBefore: seqBefore.join(','), added, hashAfter, expected: expectNext && ('#m/run/' + encodeURIComponent(expectNext.plot_no) + '/' + encodeURIComponent(expectNext.proc)), qvalEmpty, cur: cur && cur.plot_no, doneIsS1, nowIsNext, noDoneRoute, bal: LOT.balance('PL-M-S1','FORGE') }; })()`);
  P('26 잔량 0 완료: PL-M-S1 단조 20/20 [작업 완료] → 실적 +1 만 · 잔량 0 → 다음 순번 작업의 입력 화면으로 자동 이동(수량 0 · 실적 생성 0) · ● = 다음 작업 · 홈에서 PL-M-S1 = ✓ 완료 · M08 라우트 없음', s26.nowIsS1 && s26.added === 1 && s26.bal === 0 && s26.hashAfter === s26.expected && s26.qvalEmpty && s26.cur === (s26.expected||'').split('/')[2] && s26.doneIsS1 && s26.nowIsNext && s26.noDoneRoute, JSON.stringify(s26));
  // 27 정지 = 설비 컨텍스트만 해제 (원장·근태·가동기록 0) → 설비 없음 화면 + [목록에서 설비 선택](기존 설비 마스터 1벌) → 선택 → 작업 순서 복귀 · QR 우선 안내
  const s27 = X(`(()=>{ const snap0 = JSON.stringify(DB.snapshot()); location.hash='#m/home'; router(); document.getElementById('m-stop').onclick(); const s = SES.get(); const cleared = s.equipment === null && !s.current; const noeq = !!document.querySelector('.m-noeq') && !!document.getElementById('m-eq-pick'); const snap1 = JSON.stringify(DB.snapshot()); document.getElementById('m-eq-pick').onclick(); const qrFirst = !document.querySelector('#modal a[href="#m/scan"]'); const items = [...document.querySelectorAll('#modal [data-eq]')].map(b => b.dataset.eq); const master = buildEquipmentList().map(e => e.name); const fromMaster = items.length > 0 && items.every(n => master.includes(n)); document.querySelector('#modal [data-eq="프레스 1호"]').onclick(); const eqNow = SES.get().equipment && SES.get().equipment.name; const seqBack = document.querySelectorAll('.m-seq-it').length > 0; const noStopWrite = !/DB\\.set\\(|stopped|downtime|비가동/.test(String(mobileStop) + String(mobileEquipmentPicker)); return { cleared, noeq, ledgerSame: snap0 === snap1, qrFirst, fromMaster, n: items.length, eqNow, seqBack, noStopWrite }; })()`);
  P('27 [■ 정지] → 현재 설비·진행 작업 해제 · 원장 스냅샷 불변 · 설비 없음 화면 → [설비 선택] = 기존 설비 마스터 목록(buildEquipmentList · QR 링크 0) → 프레스 1호 선택 → 작업 순서 복귀 · 정지 시각/비가동/사유 저장 코드 0', s27.cleared && s27.noeq && s27.ledgerSame && s27.qrFirst && s27.fromMaster && s27.eqNow === '프레스 1호' && s27.seqBack && s27.noStopWrite, JSON.stringify(s27));
  // 28 정적: 폰(터치)에서 ▲▼ 스크롤 버튼 숨김 CSS · 현장 화면 [수동] 0 · PC 실적 등록 [수동] 유지
  const s28 = X(`(()=>{ const css = [...document.querySelectorAll('style')].map(s => s.textContent).join(''); const hide = /@media \\(pointer:coarse\\)\\{\\.scroll-nav\\{display:none !important\\}\\}/.test(css); location.hash='#m/trace'; router(); const noManualM = !document.getElementById('btn-manual') && !document.getElementById('btn-register'); SESSION.role='manager'; setUiMode('pc'); location.hash='#scan'; router(); const pcManual = !!document.getElementById('btn-manual'); SESSION.role='operator'; localStorage.removeItem('vela_ui_mode'); location.hash='#m/home'; router(); return { hide, noManualM, pcManual }; })()`);
  P('28 터치 기기 ▲▼ 스크롤 버튼 숨김(CSS pointer:coarse) · 현장 QR 탭 [수동] 0 · PC 실적 등록 [수동] 유지', s28.hide && s28.noManualM && s28.pcManual, JSON.stringify(s28));
  P('29 라벨(v0.37.4): ● 카드 [실적 등록] · 상세 [실적 등록] · 입력 화면 제목 「실적 등록 ·」 · 저장 버튼 [등록] · 「작업 시작」 문구 0', X(`(()=>{ location.hash='#m/home'; router(); const home = document.querySelector('.m-seq-it.now'); const a = home && /실적 등록/.test(home.querySelector('a.m-btn.primary').textContent); const j = mobileJobs(SES.get()).jobs[0]; location.hash='#m/job/'+j.plot_no+'/'+j.proc; router(); const b = /실적 등록/.test(document.querySelector('a.m-btn.primary, button.m-btn.primary').textContent); location.hash='#m/run/'+j.plot_no+'/'+j.proc; router(); const c = /^실적 등록 ·/.test(document.querySelector('.m-title').textContent.trim()) && document.getElementById('m-done').textContent.trim() === '등록'; const d = !/작업 시작/.test(String(VIEWS.m_home) + String(VIEWS.m_job) + String(VIEWS.m_run)); return a && b && c && d; })()`), '');
  const s30 = X(`(()=>{ const tabs = [...document.querySelectorAll('.m-tabs a')].map(a => a.textContent.trim()); const a = tabs.some(t => /주의$/.test(t)) && !tabs.some(t => /확인 필요/.test(t)) && M_LABEL.pending === '확인 필요'; location.hash='#m/trace'; router(); const b = !!document.getElementById('m-tr-cam-err') && !!document.getElementById('m-tr-err') && !!document.getElementById('m-tr-q'); const src = String(VIEWS.m_trace); const c = /setTimeout\\(startCam, 400\\)/.test(src) && /qrbox:\\(w,h\\)/.test(src) && /NotAllowed\\|Permission\\|denied/.test(src); const css = [...document.querySelectorAll('style')].map(s => s.textContent).join(''); const d = /\\.m-cam\\{width:min\\(62vw,260px\\);aspect-ratio:1/.test(css); location.hash='#m/home'; router(); return { a, b, c, d, tabs: tabs.join('|') }; })()`);
  P('30 v0.37.5: 하단 탭 「주의」(「확인 필요」 메뉴명 0 · 수량 라벨 「확인 필요」 유지) · 조회 카메라 = 라이브러리 대기·qrbox 함수·오류 배너 요소 · 카메라 정사각형 CSS', s30.a && s30.b && s30.c && s30.d, JSON.stringify(s30));
  P('31 v0.37.6 주의 화면 설명: 한 줄 설명 + 네 가지 사유 범례(HOLD·판정 대기·확인 필요·납기) + 관리자 PC 안내 · 빈 상태 안내', X(`(()=>{ location.hash='#m/check'; router(); const t = document.getElementById('view').textContent; const ok = !!document.querySelector('.m-sub') && /품질 HOLD/.test(t) && /품질 판정 대기/.test(t) && /확인 필요/.test(t) && /납기 지남/.test(t) && /관리자가 PC/.test(t) && document.querySelectorAll('.m-legend-row').length === 4; location.hash='#m/home'; router(); return ok; })()`), '');
  P('버전 v0.38.21 · 데모 시드 worker 사용자(U-DEMO-W 홍길동)', X(`APP_VERSION`) === 'v0.38.21' && X(`DB.get('users','U-DEMO-W') && DB.get('users','U-DEMO-W').role`) === 'worker' && X(`DEMO_SEED_VER`) === 7, X(`APP_VERSION`));
} catch(e){ R.push({ n:'FATAL', ok:false, note: e.stack || e.message }); }
let fail = 0;
R.forEach(r => { if(!r.ok) fail++; console.log(`[${r.ok?'PASS':'FAIL'}] ${r.n}${r.note?`  — ${r.note}`:''}`); });
console.log(`\nMOBILE TOTAL ${R.length} · PASS ${R.length-fail} · FAIL ${fail}`);
// ★ v0.38.20 (GPT Gate) — FAIL 또는 항목 수 불일치(중도 종료) = 종료코드 1
if(R.length !== 39) console.log(`[FAIL] 항목 수 ${R.length} ≠ 기대 39 (중도 종료·누락)`);
process.exit((fail || R.length !== 39) ? 1 : 0);
})();
function shiftNow(w){ return w.__X(`shiftAt(Date.now()).code`); }
